-
  name: app

  type: php:8.2

  dependencies:
    php:
      composer/composer: "^2"

  runtime:
    extensions:
      - apcu
      - blackfire
      - ctype
      - iconv
      - mbstring
      - pdo_pgsql
      - sodium
      - xsl

  variables:
    php:
      opcache.preload: config/preload.php
  build:
    flavor: none

  disk: 1024

  web:
    locations:
      "/":
        root: "public"
        expires: 1h
        passthru: "/index.php"

  mounts:
    "/var": { source: local, source_path: var }

  relationships:
    database: "database:postgresql"

  hooks:
    build: |
      set -x -e

      curl -fs https://get.symfony.com/cloud/configurator | bash

      NODE_VERSION=18 symfony-build

    deploy: |
      set -x -e

      symfony-deploy

  crons:
    security-check:
      # Check that no security issues have been found for PHP packages deployed in production
      # See https://github.com/fabpot/local-php-security-checker
      spec: "50 23 * * *"
      cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape php-security-checker; fi

  workers:
    messenger:
      commands:
        # Consume "async" messages (as configured in the routing section of config/packages/messenger.yaml)
        start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async

- # Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

  # A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
  # with the app.
  name: mercure

  # The runtime the application uses.
  # Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
  type: golang:1.18

  # How many resources to devote to the app. Defaults to AUTO in production environments.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#sizes
  size: L

  # The size of the persistent disk of the application (in MB). Minimum value is 128.
  disk: 2048

  # Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
  mounts:
    "database": { source: local, source_path: "database" }
    "/.local": { source: local, source_path: .local }
    "/.config": { source: local, source_path: .config }

  # The web key configures the web server running in front of your app.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#web
  web:
    # Commands are run once after deployment to start the application process.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#web-commands
    commands:
      # The command to launch your app. If it terminates, it’s restarted immediately.
      start: ./mercure run 
      # start: ./mercure run --config .config/Caddyfile.platform_sh
    # Each key in locations is a path on your site with a leading /.
    # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
    locations:
      "/":
        # Whether to forward disallowed and missing resources from this location to the app. A string is a path
        # with a leading / to the controller, such as /index.php.
        passthru: true
        # Whether to allow scripts to run. Doesn’t apply to paths specified in passthru. Meaningful only on PHP containers.
        scripts: false
        # Whether to allow serving files which don’t match a rule.
        allow: true
        request_buffering:
          enabled: false
        headers:
          Access-Control-Allow-Origin: "*"

  # Variables to control the environment. More information: https://docs.platform.sh/create-apps/app-reference.html#variables
  variables:
    env:
      MERCUREVERSION: '0.16.2'
      SERVER_NAME: ":8888"
      MERCURE_TRANSPORT_URL: "bolt:///var/run/mercure.db?size=1000&cleanup_frequency=0.5"
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origin *
        publish_origins *
        subscriptions
        demo
        ui
      GLOBAL_OPTIONS: |
        auto_https off
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"

  # Specifies a default set of build tasks to run. Flavors are language-specific.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#build
  build:
    flavor: none

  # Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
  # More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
  hooks:
    # The build hook is run after any build flavor.
    # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
    build: |
      # Install Mercure using cache
      echo "${MERCUREVERSION}"
      FILE="mercure_Linux_x86_64.tar.gz"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
        URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
        echo "Downloading $URL"
        wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
        echo "Found $FILE in cache, using cache"
      fi
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE

  # Information on the app's source code and operations that can be run on it.
  # More information: https://docs.platform.sh/create-apps/app-reference.html#source
  source:
    # The path where the app code lives. Defaults to the directory of the .platform.app.yaml file. Useful for multi-app setups.
    root: mercure
