"https://{all}/": { type: upstream, upstream: "app:http" }
"http://{all}/": { type: redirect, to: "https://{all}/" }
https://mercure.{all}:
  type: upstream
  upstream: "mercure:http"
  id: mercure
  cache:
    enabled: false
